---
# Główny task instalacji serwera repozytorium pakietów BA
# marcin_stec <at> pl.ibm.com

  - name: Status repozytorium
    stat:
      path: "{{ ba_root }}/repodata"
    register: repo

  - name: Unikanie nadpisania istniejącego repozytorium
    assert:
      fail_msg: "Repozytorium {{ ba_root }}/repodata istnieje. Pierdolę, nie robię."
      success_msg: "Nie znaleziono katalogu {{ ba_root }}/repodata. Kontynuję konfigurację"
    when: repo.stat.exists


  - name: Podkatalog repozytorium
    file:
      name: "{{ repo_dir }}"
      state: directory
      owner: "lighttpd"
      group: "lighttpd"
      mode: 0755
    tags:
      - "FS"

  - name: Podkatalog na archiwa
    file:
      name: "{{ arch_dir }}"
      state: directory
      owner: "lighttpd"
      group: "lighttpd"
      mode: 0755
    tags:
      - "FS"

  - name: Sciąganie paczki BA z IBM
    get_url:
      url: "{{ latest_ba_url }}"
      dest: "{{ arch_dir }}/{{ latest_ba_tar }}"

  - name: "Odpakowanie TARa z klientem BA do {{ repo_dir }}"
    unarchive:
      src: "{{ arch_dir }}/{{ latest_ba_tar }}"
      dest: "{{ repo_dir }}"
      creates: "{{ repo_dir }}/update.txt"
    become_user: "lighttpd"
    tags:
      - "HTTPD"
      - "BA"

  - name: "Zezwolenie na directory browsing w {{ repo_dir }}"
    copy:
      src: dirlisting.conf
      dest: "/etc/lighttpd/conf.d/"
    tags:
      - "HTTPD"

  - name: "Dodawanie polityk SELinux dla katalogu {{ www_root}}"
    sefcontext:
      target: '{{ www_root }}(/.*)?'
      seuser: "system_u"
      setype: "httpd_sys_rw_content_t"
      state: present
    when: ansible_facts.selinux.status == 'enabled'
    tags:
      - "SEC"
      - "HTTPD"
      - "BA"

  - name: "Tworzenie repozytorium RPM w {{ repo_dir }}"
    command: 
      cmd: createrepo {{ repo_dir }}
      creates: "{{ repo_dir }}/repodata"
    become_user: "lighttpd"
    tags:
      - "BA"
      - "REPO"

  - name: "Generowanie pliku repozytorium {{ ba_root }}/ba.repo"
    template:
      src: ba.repo.j2
      dest: "{{ repo_dir }}/ba.repo"
      owner: "lighttpd"
      group: "lighttpd"
      mode: 0644
    tags:
      - "BA"
      - "REPO"

  - name: "Ustawianie kontekstu SELinux na {{ doc_root }}"
    command: restorecon -irv "{{ doc_root }}"
    when: ansible_facts.selinux.status == 'enabled'
    tags:
      - "SEC"
      - "HTTPD"
      - "BA"